seven_dof_arm:
  gazebo_ros_control:
    pid_gains:
      shoulder_pan_joint: {p: 100.0, i: 0.01, d: 10.0}
      shoulder_pitch_joint: {p: 100.0, i: 0.01, d: 10.0}
      elbow_roll_joint: {p: 50.0, i: 0.005, d: 5.0}
      elbow_pitch_joint: {p: 50.0, i: 0.005, d: 5.0}
      wrist_roll_joint: {p: 20.0, i: 0.002, d: 2.0}
      wrist_pitch_joint: {p: 20.0, i: 0.002, d: 2.0}
      gripper_roll_joint: {p: 10.0, i: 0.001, d: 1.0}
      finger_joint1: {p: 5.0, i: 0.001, d: 0.5}
      finger_joint2: {p: 5.0, i: 0.001, d: 0.5}

